# Generated by Django 5.0.4 on 2024-04-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa', models.CharField(max_length=50)),
                ('carro', models.CharField(max_length=50)),
                ('fecha_adquisicion', models.DateField(null=True)),
            ],
        ),
    ]
